from enum import IntEnum


__all__ = ['BinLog', 'FieldType']


class BinLog(IntEnum):
    UNKNOWN_EVENT = 0x00
    START_EVENT_V3 = 0x01
    QUERY_EVENT = 0x02
    STOP_EVENT = 0x03
    ROTATE_EVENT = 0x04
    INTVAR_EVENT = 0x05
    LOAD_EVENT = 0x06
    SLAVE_EVENT = 0x07
    CREATE_FILE_EVENT = 0x08
    APPEND_BLOCK_EVENT = 0x09
    EXEC_LOAD_EVENT = 0x0a
    DELETE_FILE_EVENT = 0x0b
    NEW_LOAD_EVENT = 0x0c
    RAND_EVENT = 0x0d
    USER_VAR_EVENT = 0x0e
    FORMAT_DESCRIPTION_EVENT = 0x0f
    XID_EVENT = 0x10
    BEGIN_LOAD_QUERY_EVENT = 0x11
    EXECUTE_LOAD_QUERY_EVENT = 0x12
    TABLE_MAP_EVENT = 0x13
    PRE_GA_WRITE_ROWS_EVENT = 0x14
    PRE_GA_UPDATE_ROWS_EVENT = 0x15
    PRE_GA_DELETE_ROWS_EVENT = 0x16
    WRITE_ROWS_EVENT_V1 = 0x17
    UPDATE_ROWS_EVENT_V1 = 0x18
    DELETE_ROWS_EVENT_V1 = 0x19
    INCIDENT_EVENT = 0x1a
    HEARTBEAT_LOG_EVENT = 0x1b
    IGNORABLE_LOG_EVENT = 0x1c
    ROWS_QUERY_LOG_EVENT = 0x1d
    WRITE_ROWS_EVENT_V2 = 0x1e
    UPDATE_ROWS_EVENT_V2 = 0x1f
    DELETE_ROWS_EVENT_V2 = 0x20
    GTID_LOG_EVENT = 0x21
    ANONYMOUS_GTID_LOG_EVENT = 0x22
    PREVIOUS_GTIDS_LOG_EVENT = 0x23


class FieldType(IntEnum):
    DECIMAL = 0
    TINY = 1
    SHORT = 2
    LONG = 3
    FLOAT = 4
    DOUBLE = 5
    NULL = 6
    TIMESTAMP = 7
    LONGLONG = 8
    INT24 = 9
    DATE = 10
    TIME = 11
    DATETIME = 12
    YEAR = 13
    NEWDATE = 14
    VARCHAR = 15
    BIT = 16
    TIMESTAMP2 = 17
    DATETIME2 = 18
    TIME2 = 19
    NEWDECIMAL = 246
    ENUM = 247
    SET = 248
    TINY_BLOB = 249
    MEDIUM_BLOB = 250
    LONG_BLOB = 251
    BLOB = 252
    VAR_STRING = 253
    STRING = 254
    GEOMETRY = 255

    CHAR = TINY
    INTERVAL = ENUM
